apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics-test
  newTag: 1c3e77b0ba86458c329a0d070a25441056d8fb0b
kind: Kustomization
namespace: xihe-test-v2
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-deployment.yaml
