apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-async-server
  newTag: 6366478c65561c9182eaebfc060d519b1e1ef757
kind: Kustomization
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn4-x86
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: zhouzixian
  kubernetes.ops.region: hk
namespace: xihe-test-v2
resources:
- ingress.yaml
- deployment.yaml
