apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^~/resource/                  https://gitee.com/mindspore/book                                    redirect;
      rewrite ^/icla                        https://clasign.osinfra.cn/sign/gitee_mindspore-1614155835277678289 redirect;
      rewrite ^/ecosystem/libraries         /ecosystem                                                          redirect;
      rewrite ^/ecosystem/tutorials         /ecosystem                                                          redirect;
      rewrite ^/ecosystem/models            /ecosystem                                                          redirect;
      rewrite ^/community/evangelist        /community/developer                                                redirect;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Content-Security-Policy "script-src 'self' *.baidu.com 'unsafe-inline' 'unsafe-eval' https://cdn.bootcss.com https://cdn.mathjax.org https://cdnjs.cloudflare.com/ https://cdn.jsdelivr.net/; object-src 'none'; frame-src https://player.bilibili.com https://www.bilibili.com";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Frame-Options "DENY";
      add_header Cache-Control "no-cache";
      add_header Pragma "no-cache";
      add_header X-Content-Type-Options "nosniff";
    nginx.ingress.kubernetes.io/limit-rpm: "500"
  name: mindspore-website-www-ingress
  namespace: website-revision
spec:
  tls:
    - hosts:
      - www.mindspore.cn
      secretName: website-tls
  rules:
    - host: www.mindspore.cn
      http:
        paths:
        - backend:
            serviceName: website-service
            servicePort: 8080
          path: /

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.mindspore.cn$request_uri
  name: mindspore-website-ingress
  namespace: website-revision
spec:
  tls:
  - hosts:
      - mindspore.cn
    secretName: website-tls
  rules:
    - host: mindspore.cn
