apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  component: internal-server
nameSuffix: -internal-server
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-internal-server
  newTag: main-fd17336
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-internal-server
  newTag: 9d87ab55fa71641f1ed43c8f1ed3f304fd6cff3e
